### ISSUE TITLE
How to get reference of the container deep in tree?

### ISSUE THREAD

**Issue by binoypatel** [escamoteur/get_it#1]
Hi

Thanks for this great work of bringing IoC/Locator to Dart. I have a question, how can I get the reference of GetIt in which I have registered few classes on the different page? For example, in app.dart I have created GetIt instance and registered some classes in main() method, now I need this GetIt instance in one of my entry page let say userEditView.dart, how should I get it? I don't want to use InheritedWidget.

Thanks,
Binoy

**Comment by escamoteur** [comment]
Just assign your getIt instance to a global variable. As Dart supports global variables I decided not to implement getIt as Singleton.

**Comment by binoypatel** [comment]
Thanks, I got this then and I truly don't miss Splat :)
```
splat.dart
import 'package:get_it/get_it.dart';

class Locator {
  static final Locator _singleton = new Locator._internal();
  static final GetIt _current = GetIt();

  factory Locator() {
    return _singleton;
  }

  static GetIt get current => _current;

  Locator._internal();
}
```

**Comment by escamoteur** [comment]
You really don't have to use a Singleton just use a global variable. Way shorter to write Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [escamoteur/get_it] How to get reference of the container deep in tree? (#1)Von: Binoy An: escamoteur/get_it Cc: escamoteur ,Comment Thanks, I got this then and I truly don't miss Splat :)
splat.dart
import 'package:get_it/get_it.dart';

class Locator {
  static final Locator _singleton = new Locator._internal();
  static final GetIt _current = GetIt();

  factory Locator() {
    return _singleton;
  }

  static GetIt get current => _current;

  Locator._internal();
}


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/escamoteur/get_it/issues/1#issuecomment-392182888","url":"https://github.com/escamoteur/get_it/issues/1#issuecomment-392182888","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/escamoteur/get_it","title":"escamoteur/get_it","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/escamoteur/get_it"}},"updates":{"snippets":[{"icon":"PERSON","message":"@binoypatel in #1: Thanks, I got this then and I truly don't miss Splat :)\r\n```\r\nsplat.dart\r\nimport 'package:get_it/get_it.dart';\r\n\r\nclass Locator {\r\n  static final Locator _singleton = new Locator._internal();\r\n  static final GetIt _current = GetIt();\r\n\r\n  factory Locator() {\r\n    return _singleton;\r\n  }\r\n\r\n  static GetIt get current =\u003e _current;\r\n\r\n  Locator._internal();\r\n}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/escamoteur/get_it/issues/1#issuecomment-392182888"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [escamoteur/get_it] How to get reference of the container deep in tree? (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Binoy**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@binoypatel",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"escamoteur/get_it\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/escamoteur/get_it/issues/1#issuecomment-392182888"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339325948\n}"
}
],
"themeColor": "26292E"
}
